config:
  build_jobs: 2
  build_stage:
  - $spack/var/spack/stage

  install_tree:
    projections:
      all: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}/${VERSION}-${HASH:7}

  template_dirs:
    - $HOME/.spack/templates

