config:
  build_jobs: 4
  build_stage:
  - $spack/var/spack/stage

  install_tree:
    projections:
      all: ${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}/${VERSION}-${HASH:7}

  template_dirs:
    - /share/Apps/spackenv/etc/templates
    - $spack/etc/templates
    - $HOME/.spack/templates


